In [1]:
import pandas as pd
import numpy as np
from ast import literal_eval
pd.set_option('display.max_columns', None)

In [2]:
data_df = pd.read_csv("../kham_pha_du_lieu/animals_split_info.csv", index_col = 0)
# data_df = data_df.drop(columns = data_df.columns[0], axis = 1)
data_df.head()

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,Population size,Life span,Top speed,Weight,Height,Length,Introduced countries,Seas,Islands,Biome,Climate,Seasonal behavior,Predators,Bird's call,Mating behavior,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status,Attributes,Continents,Subcontinents,Countries,Regions,Wwf biomes,Group name,Diet,Biogeographical realms,Lifestyle,Oceans
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,"400,000",10-20 yrs,75 km/h,16-60 kg,80-85 cm,105-160 cm,NaN,NaN,NaN,"['Wetlands ', 'Shrubland', 'Forest', 'Mountain...","['Temperate', 'Cold', 'Polar', 'Tropical']",Not a migrant,NaN,NaN,Monogamy,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC),"['Nocturnal', 'Carnivore', 'Scavenger', 'Terre...","['Asia', ' Europe', ' North America', ' Africa']","['South Asia', ' Western Asia', ' Southeast As...","['Albania', ' Armenia', ' Azerbaijan', ' Belar...","['Czech Republic', ' Estonia', ' Finland', ' F...","['Nearctic', ' Palearctic', ' Indomalayan', ' ...","['pack', ' route', ' rout']","['Carnivore', '', 'Scavenger']",['Greenland'],"['Terrestrial', ' Cursorial', ' Altricial', ' ...",[]
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,"2,154-3,159",10-15 yrs,96 km/h,65-306 kg,NaN,200-390 cm,NaN,NaN,NaN,"['Forest', 'Rainforest', 'Montane forest', 'Ri...","['Tropical', 'Temperate']",Not a migrant,NaN,NaN,Polygyny,November-April,103 days,1-7 cubs,18 mos-3 yrs,NaN,NaN,cub,NaN,Decreasing,Endangered (EN),"['Nocturnal', 'Carnivore', 'Cursorial', 'Terre...",['Asia'],"['South Asia', ' Southeast Asia', ' East Asia']","['Bangladesh', ' Bhutan', ' China', ' India'...",['Thailand'],"['Palearctic', ' Indomalayan']",[],['Carnivore'],"['Tibet', ' Yunnan']","['Cursorial', ' Terrestrial', ' Ambush predato...",[]
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,"200,000",20-50 yrs,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,NaN,NaN,NaN,"['Forest', 'Woodland']","['Temperate', 'Cold', 'Polar']","Hibernating, Migrating",NaN,NaN,"Polygynandry,",May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC),"['Crepuscular', 'Omnivore', 'Terrestrial', 'Al...","['Asia', ' Europe', ' North America']","['South Asia', ' Western Asia', ' East Asia', ...","['Albania', ' Armenia', ' Austria', ' Azerbaij...",[],"['Nearctic', ' Palearctic', ' Indomalayan']","['sloth', ' sleuth']",['Omnivore'],"['Estonia', ' Finland', ' France', ' Georgia',...","['Terrestrial', ' Altricial', ' Nomadic', ' Te...",[]
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,10-25 Thou,80-90 yrs,20 km/h,100-160 t,NaN,25-30 m,NaN,NaN,NaN,"['Oceanic pelagic zone', 'Marine', 'Neritic zo...","['Tropical', 'Temperate', 'Cold', 'Polar']",Migrating,NaN,NaN,Monogamy,winter or early spring,1 year,1 calf,8 months,cow,bull,calf,NaN,Increasing,Endangered (EN),"['Carnivore', 'Piscivores', 'Aquatic', 'Precoc...","['Africa', ' South America', ' Oceania', ' Nor...","['Sub-Saharan Africa', ' Caribbean Islands', '...","['Angola', ' Argentina', ' Australia', ' Baham...","['Chile', ' China', ' Colombia', ' Comoros', '...",[],"['pod', ' gam', ' herd', ' school', ' mod']","['Carnivore', '', 'Piscivores']","['Atlantic Ocean', ' Pacific Ocean']","['Aquatic', ' Precocial', ' Natatorial', ' Viv...","['Greenland', ' Kamchatka']"
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,"50,000",30-100 yrs,45 km/h,3-6 t,NaN,6-9 m,NaN,NaN,NaN,"['Oceanic pelagic zone', 'Marine', 'Neritic zo...","['Tropical', 'Temperate', 'Cold', 'Polar']",Partial Migrant,NaN,NaN,Polygynandry,"year-round, usually in summer",15-18 months,1 calf,2 years,cow,bull,calf,NaN,NaN,NaN,"['Diurnal', 'Carnivore', 'Aquatic', 'Precocial...","['Africa', ' Oceania', ' Antarctica', ' North ...","['North Africa', ' Caribbean Islands', ' South...","['Algeria', ' Antigua and Barbuda', ' Argentin...","['Brunei', ' Cambodia', ' Cameroon', ' Canada'...",[],"['pod', ' gam', ' herd', ' school', ' mod']",['Carnivore'],"['Arctic Ocean', ' Atlantic Ocean', ' Pacific ...","['Aquatic', ' Precocial', ' Cosmopolitan', ' N...","['Newfoundland', ' Hawaii', ' Greenland']"

In [3]:
for i in data_df:
    if type(data_df[i][0]) == str and data_df[i][0][0] == "[":
        data_df[i] = data_df[i].apply(literal_eval)

In [4]:
def stat_list_col(col, array):
    temp = pd.DataFrame(array[col])
    temp = temp.dropna()
    temp = np.array(temp[col])
    data = []
    # missing_ratio
    data.append(round((100 - (len(temp) / len(array[col]) * 100)), 1))
    # num_values
    temp = np.hstack(temp)
    temp = list(map(str.strip, temp)) # Xử lý các dấu cách đầu và cuối mỗi chuỗi
    temp = np.unique(temp, return_counts=True)
    data.append(len(temp[0]))
    # value
    temp = pd.Series(data = temp[1], index = temp[0])
    data.append(temp)
    # num_values
    return data

In [5]:
list_col_info_df = pd.DataFrame(index = ['missing_ratio', 'num_values', 'value'])
for i in data_df:
    if type(data_df[i][0]) == list:
        list_col_info_df[i] = stat_list_col(i, data_df)
list_col_info_df

,Biome,Climate,Attributes,Continents,Subcontinents,Countries,Regions,Wwf biomes,Group name,Diet,Biogeographical realms,Lifestyle,Oceans
missing_ratio,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
num_values,43,6,139,76,89,251,394,249,402,30,391,51,253
value,Abyssal zone 4 Agricultural ...,Arid 304 Cold 309 Libya ...,Aestivation 71 Algivore ...,3 Africa ...,12 Afghanistan ...,884 Afghanistan 66 Af...,65 Acre 2 Afghanis...,...,"1 ""bind"" 1 ""littl...",2941 Algivore 16 ...,3...,1784 Aesti...,10 Afghanistan ...