In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../thu_thap_du_lieu/animal_crawler/animal_info.csv')

In [3]:
df.head()

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Top speed,Weight,Height,Length,Attributes,Distribution,Habits,Diet,Mating_Habits,Population
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,...,75 km/h,16-60 kg,80-85 cm,105-160 cm,"Nocturnal,Carnivore,Scavenger,Terrestrial,Curs...","{'Geography': {'Continents': 'Asia, Europe, No...","{'Group name': 'pack, route, rout Terrestrial...","Carnivore,,Scavenger","{'Mating behavior': 'Monogamy', 'Reproduction ...","{'Population trend': 'Stable', 'Population sta..."
1,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,...,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,"Crepuscular,Omnivore,Terrestrial,Altricial,Nom...","{'Geography': {'Continents': 'Asia, Europe, No...","{'Group name': 'sloth, sleuth', 'Lifestyle': '...",Omnivore,"{'Mating behavior': 'Polygynandry,', 'Reproduc...","{'Population trend': 'Stable', 'Population sta..."
2,Koala,Animalia,Chordata,Vertebrata,Mammalia,Diprotodontia,NaN,Phascolarctidae,Phascolarctos,Phascolarctos cinereus,...,10 km/h,4-15 kg,60-85 cm,NaN,"Nocturnal,Herbivore,Folivore,Arboreal,Altricia...","{'Geography': {'Continents': 'Oceania', 'Count...","{'Lifestyle': 'Arboreal, Altricial, Terrestria...","Herbivore,,Folivore","{'Mating behavior': 'Polygyny', 'Reproduction ...","{'Population trend': 'Decreasing', 'Population..."
3,Giant Panda,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ailuropoda,Ailuropoda melanoleuca,...,32 km/h,70-160 kg,60-90 cm,1.2-1.9 m,"Crepuscular,Nocturnal,Herbivore,Folivore,Terre...","{'Geography': {'Continents': 'Asia', 'Subconti...","{'Group name': 'sleuth', 'Lifestyle': 'Terrest...","Herbivore,,Folivore","{'Mating behavior': 'Polygyny', 'Reproduction ...","{'Population trend': 'Increasing', 'Population..."
4,Lion,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera leo,...,56 km/h,120-249 kg,NaN,140-250 cm,"Nocturnal,Crepuscular,Diurnal,Scavenger,Hyperc...","{'Geography': {'Continents': 'Africa, Asia', '...","{'Group name': 'pride, sault, troop, sawt', 'L...","Scavenger,,Hypercarnivore","{'Mating behavior': 'Polygyny', 'Reproduction ...","{'Population trend': 'Decreasing', 'Population..."

In [4]:
for i in df:
    if df[i][0].find('{') != -1:
        df[i] = df[i].apply(eval)

In [5]:
element = []
# df = df.head(3)
# print(df)
def split_col(df):
    for i in df:
        if type(df[i][0]) == dict: 
            element.append(i)
    df_split_animals_info = pd.DataFrame()
    for i in df:
        if i not in element:
            df_split_animals_info[i] = df[i]
        else:
            temp3 = df[i][0].items()
            temp3 = np.array(list(temp3), dtype = object)
            df_temp2 = pd.DataFrame(columns = temp3[:, 0])
            for rows in df[i]:
                temp3 = rows.items()
                temp3 = np.array(list(temp3), dtype = object)
                if len(temp3) > 1: 
                    df_temp = pd.DataFrame(index = temp3[:, 0], data = temp3[:, 1]).T
                else:
                    df_temp = pd.DataFrame(columns = df_temp2.columns, index = [0])
                df_temp2 = pd.concat([df_temp2, df_temp], ignore_index=True)
            df_split_animals_info = df_split_animals_info.join(df_temp2)
    return df_split_animals_info

In [6]:
df_split_animals_info = split_col(df)
df_split_animals_info.head()

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,...,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC)
1,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,...,May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC)
2,Koala,Animalia,Chordata,Vertebrata,Mammalia,Diprotodontia,NaN,Phascolarctidae,Phascolarctos,Phascolarctos cinereus,...,December-March,35 days,1 joey,1 year,female,male,joey,NaN,Decreasing,Vulnerable (VU)
3,Giant Panda,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ailuropoda,Ailuropoda melanoleuca,...,March-May,5 months,1-2 cubs,18 months,sow,boar,cub,NaN,Increasing,Vulnerable (VU)
4,Lion,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera leo,...,"year-round, peak during the rainy season",110-119 days,3-6 cubs,2 years,lioness,lion,cub,NaN,Decreasing,Vulnerable (VU)

In [7]:
df_split_animals_info = split_col(df_split_animals_info)
df_split_animals_info.head()

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,...,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC)
1,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,...,May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC)
2,Koala,Animalia,Chordata,Vertebrata,Mammalia,Diprotodontia,NaN,Phascolarctidae,Phascolarctos,Phascolarctos cinereus,...,December-March,35 days,1 joey,1 year,female,male,joey,NaN,Decreasing,Vulnerable (VU)
3,Giant Panda,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ailuropoda,Ailuropoda melanoleuca,...,March-May,5 months,1-2 cubs,18 months,sow,boar,cub,NaN,Increasing,Vulnerable (VU)
4,Lion,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera leo,...,"year-round, peak during the rainy season",110-119 days,3-6 cubs,2 years,lioness,lion,cub,NaN,Decreasing,Vulnerable (VU)

In [8]:
def col_info(col, array):
    temp = pd.DataFrame(array[col])
    temp = temp.dropna()
    temp = np.array(temp[col])
    data = []
    # missing_ratio
    data.append(round((100 - (len(temp) / len(array[col]) * 100)), 1))
    # num_values
    temp = np.unique(temp, return_counts=True)
    data.append(len(temp[0]))
    # value
    temp = pd.Series(data = temp[1], index = temp[0])
    data.append(temp)
    # num_values
    return data

In [9]:
cat_col_info_df = pd.DataFrame(index = ['missing_ratio', 'num_values', 'value'])
for i in df_split_animals_info.columns:
    if df_split_animals_info[i].dtype not in [float, int]:
        cat_col_info_df[i] = col_info(i, df_split_animals_info)

cat_col_info_df

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
missing_ratio,0.0,0.0,6.7,0.0,0.0,0.0,84.3,0.0,0.1,0.0,...,86.3,78.5,76.8,85.3,88.6,88.5,84.9,100.0,11.6,11.6
num_values,6300,153,1,2,2,29,8,165,1321,5940,...,404,668,331,298,28,32,63,3,4,7
value,? Nycticebus linglom 1 AEECL's sportive ...,Abert's Squirrel 1 African Buffalo ...,Chordata 5879 dtype: int64,Animalia 421 Vertebrata 5879 dtype: i...,Chordata 421 Mammalia 5879 dtype: int64,Afrosoricida 56 Artiodactyla ...,Caniformia 192 Feliformia 100 ...,Abrocomidae 10 Acrobatidae ...,Abditomys 1 Abeomelomys 1 Abrawayaom...,Abditomys latidens 1 Abeomelomys sevia ...,...,26-35 days ...,0 to 0.01 months 1 1 ...,0 to 1 2 0 to 2 1 1 ...,1 - 1.5 yea 1 1 month 12 1 mo...,angeline 1 bitch 1...,billy 2 boar 8...,"Fawn, twins 1 Infant 5 Jo...",1 month 1 10 days 1 23 days 1 dtype: ...,Decreasing 1884 Increasing 103 Stable ...,Critically endangered (CR) 232 Data defici...

In [11]:
df_split_animals_info.to_csv('animals_split_info.csv')