In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../thu_thap_du_lieu/animal_crawler/animals_info.csv')

In [3]:
df.head()

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Top speed,Weight,Height,Length,Attributes,Distribution,Habits,Diet,Mating_Habits,Population
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,...,75 km/h,16-60 kg,80-85 cm,105-160 cm,"Nocturnal,Carnivore,Scavenger,Terrestrial,Curs...","{'Geography': {'Continents': 'Asia, Europe, No...","{'Group name': 'pack, route, rout', 'Lifestyle...","Carnivore,,Scavenger","{'Mating behavior': 'Monogamy', 'Reproduction ...","{'Population trend': 'Stable', 'Population sta..."
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,...,96 km/h,65-306 kg,NaN,200-390 cm,"Nocturnal,Carnivore,Cursorial,Terrestrial,Ambu...","{'Geography': {'Continents': 'Asia', 'Subconti...","{'Lifestyle': 'Cursorial, Terrestrial, Ambush ...",Carnivore,"{'Mating behavior': 'Polygyny', 'Reproduction ...","{'Population trend': 'Decreasing', 'Population..."
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,...,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,"Crepuscular,Omnivore,Terrestrial,Altricial,Nom...","{'Geography': {'Continents': 'Asia, Europe, No...","{'Group name': 'sloth, sleuth', 'Lifestyle': '...",Omnivore,"{'Mating behavior': 'Polygynandry,', 'Reproduc...","{'Population trend': 'Stable', 'Population sta..."
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,...,20 km/h,100-160 t,NaN,25-30 m,"Carnivore,Piscivores,Aquatic,Precocial,Natator...","{'Geography': {'Continents': 'Africa, South Am...","{'Group name': 'pod, gam, herd, school, mod', ...","Carnivore,,Piscivores","{'Mating behavior': 'Monogamy', 'Reproduction ...","{'Population trend': 'Increasing', 'Population..."
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,...,45 km/h,3-6 t,NaN,6-9 m,"Diurnal,Carnivore,Aquatic,Precocial,Cosmopolit...","{'Geography': {'Continents': 'Africa, Oceania,...","{'Group name': 'pod, gam, herd, school, mod', ...",Carnivore,"{'Mating behavior': 'Polygynandry', 'Reproduct...",{'Population status': 'Data deficient (DD)'}

In [4]:
df.shape

(29357, 22)

In [5]:
df = df.dropna(subset=['Top speed', 'Weight', 'Length'], how='all')
df = df.reset_index(drop = True)
# df.drop('index', inplace = True)
df.head()

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Top speed,Weight,Height,Length,Attributes,Distribution,Habits,Diet,Mating_Habits,Population
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,...,75 km/h,16-60 kg,80-85 cm,105-160 cm,"Nocturnal,Carnivore,Scavenger,Terrestrial,Curs...","{'Geography': {'Continents': 'Asia, Europe, No...","{'Group name': 'pack, route, rout', 'Lifestyle...","Carnivore,,Scavenger","{'Mating behavior': 'Monogamy', 'Reproduction ...","{'Population trend': 'Stable', 'Population sta..."
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,...,96 km/h,65-306 kg,NaN,200-390 cm,"Nocturnal,Carnivore,Cursorial,Terrestrial,Ambu...","{'Geography': {'Continents': 'Asia', 'Subconti...","{'Lifestyle': 'Cursorial, Terrestrial, Ambush ...",Carnivore,"{'Mating behavior': 'Polygyny', 'Reproduction ...","{'Population trend': 'Decreasing', 'Population..."
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,...,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,"Crepuscular,Omnivore,Terrestrial,Altricial,Nom...","{'Geography': {'Continents': 'Asia, Europe, No...","{'Group name': 'sloth, sleuth', 'Lifestyle': '...",Omnivore,"{'Mating behavior': 'Polygynandry,', 'Reproduc...","{'Population trend': 'Stable', 'Population sta..."
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,...,20 km/h,100-160 t,NaN,25-30 m,"Carnivore,Piscivores,Aquatic,Precocial,Natator...","{'Geography': {'Continents': 'Africa, South Am...","{'Group name': 'pod, gam, herd, school, mod', ...","Carnivore,,Piscivores","{'Mating behavior': 'Monogamy', 'Reproduction ...","{'Population trend': 'Increasing', 'Population..."
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,...,45 km/h,3-6 t,NaN,6-9 m,"Diurnal,Carnivore,Aquatic,Precocial,Cosmopolit...","{'Geography': {'Continents': 'Africa, Oceania,...","{'Group name': 'pod, gam, herd, school, mod', ...",Carnivore,"{'Mating behavior': 'Polygynandry', 'Reproduct...",{'Population status': 'Data deficient (DD)'}

In [6]:
for i in df:
    if df[i][0].find('{') != -1:
        df[i] = df[i].apply(eval)

In [7]:

# df = df.head(3)
# print(df)
def split_col(df):
    element = []
    for i in df:
        if type(df[i][0]) == dict: 
            element.append(i)
    df_split_animals_info = pd.DataFrame()
    for i in df:
        if i not in element:
            df_split_animals_info[i] = df[i]
        else:
            temp3 = df[i][0].items()
            temp3 = np.array(list(temp3), dtype = object)
            df_temp2 = pd.DataFrame(columns = temp3[:, 0])
            for rows in df[i]:
                if type(rows) != float:
                    temp3 = rows.items()
                else:
                    temp3 = []
                temp3 = np.array(list(temp3), dtype = object)
                if len(temp3) > 1: 
                    df_temp = pd.DataFrame(index = temp3[:, 0], data = temp3[:, 1]).T
                else:
                    df_temp = pd.DataFrame(columns = df_temp2.columns, index = [0])
                df_temp2 = pd.concat([df_temp2, df_temp], ignore_index=True)
            df_split_animals_info = df_split_animals_info.join(df_temp2)
    return df_split_animals_info

In [8]:
df_split_animals_info = split_col(df)
df_split_animals_info.head()

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,...,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC)
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,...,November-April,103 days,1-7 cubs,18 mos-3 yrs,NaN,NaN,cub,NaN,Decreasing,Endangered (EN)
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,...,May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC)
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,...,winter or early spring,1 year,1 calf,8 months,cow,bull,calf,NaN,Increasing,Endangered (EN)
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,...,"year-round, usually in summer",15-18 months,1 calf,2 years,cow,bull,calf,NaN,NaN,NaN

In [9]:
df_split_animals_info = split_col(df_split_animals_info)
df_split_animals_info.head()

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,...,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC)
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,...,November-April,103 days,1-7 cubs,18 mos-3 yrs,NaN,NaN,cub,NaN,Decreasing,Endangered (EN)
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,...,May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC)
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,...,winter or early spring,1 year,1 calf,8 months,cow,bull,calf,NaN,Increasing,Endangered (EN)
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,...,"year-round, usually in summer",15-18 months,1 calf,2 years,cow,bull,calf,NaN,NaN,NaN

In [10]:
def col_info(col, array):
    temp = pd.DataFrame(array[col])
    temp = temp.dropna()
    temp = np.array(temp[col])
    data = []
    # missing_ratio
    data.append(round((100 - (len(temp) / len(array[col]) * 100)), 1))
    # num_values
    temp = np.unique(temp, return_counts=True)
    data.append(len(temp[0]))
    # value
    temp = pd.Series(data = temp[1], index = temp[0])
    data.append(temp)
    # num_values
    return data

In [11]:
cat_col_info_df = pd.DataFrame(index = ['missing_ratio', 'num_values', 'value'])
for i in df_split_animals_info.columns:
    if df_split_animals_info[i].dtype not in [float, int]:
        cat_col_info_df[i] = col_info(i, df_split_animals_info)

cat_col_info_df

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
missing_ratio,0.0,0.0,1.0,32.7,0.0,0.0,76.1,0.0,0.2,0.0,...,50.0,52.4,23.7,43.6,65.3,65.3,43.2,76.7,10.4,10.4
num_values,3237,24,2,2,9,80,15,387,1622,3218,...,662,761,684,584,34,39,85,340,4,7
value,Aardvark 1 Aardwolf ...,African Wild Ass 1 American Crow ...,Chordata 3135 Mollusca 69 dtype: int64,Animalia 31 Vertebrata 2148 dtype: i...,Amphibia 79 Animalia 2 Aves ...,Accipitriformes 67 Afrosoricida 25 An...,Alcedini 9 Caniformia 158 ...,Abrocomidae 1 Accipitridae 60 Acro...,Abrawayaomys 1 Abrocoma 1 Acan...,Abrawayaomys ruschii 1 Abrocoma cin...,...,26-35 days ...,0 to 0.01 months 1 1 ...,0 to 1 2 0 to 2 ...,&gt;2 weeks 1 0 days ...,angeline 1 bitch 1...,billy 2 boar 8...,"Fawn, twins 1 Hatchling 1 In...",1 month 13 1-3 months 1 1.5 months...,Decreasing 1303 Increasing 294 Stable ...,Critically endangered (CR) 130 Data defici...

In [12]:
df_split_animals_info.to_csv('animals_split_info.csv')

In [13]:
pd.set_option('display.max_columns', None)
df_split_animals_info.head()

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,Population size,Life span,Top speed,Weight,Height,Length,Attributes,Continents,Subcontinents,Countries,Regions,Biogeographical realms,Wwf biomes,Oceans,Introduced countries,Seas,Islands,Biome,Climate,Group name,Lifestyle,Seasonal behavior,Predators,Bird's call,Diet,Mating behavior,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,"400,000",10-20 yrs,75 km/h,16-60 kg,80-85 cm,105-160 cm,"Nocturnal,Carnivore,Scavenger,Terrestrial,Curs...","Asia, Europe, North America, Africa","South Asia, Western Asia, Southeast Asia, East...","Albania, Armenia, Azerbaijan, Belarus, Bhutan,...","Czech Republic, Estonia, Finland, France, Geor...",Greenland,"Nearctic, Palearctic, Indomalayan, Afrotropical",NaN,NaN,NaN,NaN,"[Wetlands , Shrubland, Forest, Mountains, Anth...","[Temperate, Cold, Polar, Tropical]","pack, route, rout","Terrestrial, Cursorial, Altricial, Pack hunter...",Not a migrant,NaN,NaN,"Carnivore,,Scavenger",Monogamy,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC)
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,"2,154-3,159",10-15 yrs,96 km/h,65-306 kg,NaN,200-390 cm,"Nocturnal,Carnivore,Cursorial,Terrestrial,Ambu...",Asia,"South Asia, Southeast Asia, East Asia","Bangladesh, Bhutan, China, India, Indonesia,...",Thailand,"Tibet, Yunnan","Palearctic, Indomalayan",NaN,NaN,NaN,NaN,"[Forest, Rainforest, Montane forest, Riparian,...","[Tropical, Temperate]",NaN,"Cursorial, Terrestrial, Ambush predator, Altri...",Not a migrant,NaN,NaN,Carnivore,Polygyny,November-April,103 days,1-7 cubs,18 mos-3 yrs,NaN,NaN,cub,NaN,Decreasing,Endangered (EN)
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,"200,000",20-50 yrs,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,"Crepuscular,Omnivore,Terrestrial,Altricial,Nom...","Asia, Europe, North America","South Asia, Western Asia, East Asia, Central A...","Albania, Armenia, Austria, Azerbaijan, Belarus...",NaN,"Estonia, Finland, France, Georgia, Greece, Ind...","Nearctic, Palearctic, Indomalayan",NaN,NaN,NaN,NaN,"[Forest, Woodland]","[Temperate, Cold, Polar]","sloth, sleuth","Terrestrial, Altricial, Nomadic, Territorial, ...","Hibernating, Migrating",NaN,NaN,Omnivore,"Polygynandry,",May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC)
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,10-25 Thou,80-90 yrs,20 km/h,100-160 t,NaN,25-30 m,"Carnivore,Piscivores,Aquatic,Precocial,Natator...","Africa, South America, Oceania, North America,...","Sub-Saharan Africa, Caribbean Islands, South A...","Angola, Argentina, Australia, Bahamas, Banglad...","Chile, China, Colombia, Comoros, Costa Rica, C...","Atlantic Ocean, Pacific Ocean",NaN,"Greenland, Kamchatka",NaN,NaN,NaN,"[Oceanic pelagic zone, Marine, Neritic zone]","[Tropical, Temperate, Cold, Polar]","pod, gam, herd, school, mod","Aquatic, Precocial, Natatorial, Viviparous, Co...",Migrating,NaN,NaN,"Carnivore,,Piscivores",Monogamy,winter or early spring,1 year,1 calf,8 months,cow,bull,calf,NaN,Increasing,Endangered (EN)
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,"50,000",30-100 yrs,45 km/h,3-6 t,NaN,6-9 m,"Diurnal,Carnivore,Aquatic,Precocial,Cosmopolit...","Africa, Oceania, Antarctica, North America, So...","North Africa, Caribbean Islands, South Asia, C...","Algeria, Antigua and Barbuda, Argentina, Austr...","Brunei, Cambodia, Cameroon, Canada, Cape Verde...","Arctic Ocean, Atlantic Ocean, Pacific Ocean",NaN,"Newfoundland, Hawaii, Greenland",NaN,NaN,NaN,"[Oceanic pelagic zone, Marine, Neritic zone, E...","[Tropical, Temperate, Cold, Polar]","pod, gam, herd, school, mod","Aquatic, Precocial, Cosmopolitan, Natatorial, ...",Partial Migrant,NaN,NaN,Carnivore,Polygynandry,"year-round, usually in summer",15-18 months,1 calf,2 years,cow,bull,calf,NaN,NaN,NaN

In [14]:
element = np.array(['Attributes', 'Continents', 'Subcontinents', 'Countries', 'Regions', 'Wwf biomes', 'Group name', 'Diet', 'Biogeographical realms', 'Lifestyle', 'Oceans'])
splits = [df_split_animals_info[col].str.split(pat=',', expand=False) for col in element]

splits = pd.DataFrame(splits).T
# print(splits.shape)
# print(splits.head())

In [15]:
df_split_animals_info.drop(element, axis=1, inplace=True)
data_df = pd.concat([df_split_animals_info, splits], axis = 1)
data_df = data_df.drop(columns = data_df.columns[0], axis = 1)
data_df
# df_split_animals_info

,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,Population size,Life span,Top speed,Weight,Height,Length,Introduced countries,Seas,Islands,Biome,Climate,Seasonal behavior,Predators,Bird's call,Mating behavior,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status,Attributes,Continents,Subcontinents,Countries,Regions,Wwf biomes,Group name,Diet,Biogeographical realms,Lifestyle,Oceans
0,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,"400,000",10-20 yrs,75 km/h,16-60 kg,80-85 cm,105-160 cm,NaN,NaN,NaN,"[Wetlands , Shrubland, Forest, Mountains, Anth...","[Temperate, Cold, Polar, Tropical]",Not a migrant,NaN,NaN,Monogamy,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC),"[Nocturnal, Carnivore, Scavenger, Terrestrial,...","[Asia, Europe, North America, Africa]","[South Asia, Western Asia, Southeast Asia, ...","[Albania, Armenia, Azerbaijan, Belarus, Bh...","[Czech Republic, Estonia, Finland, France, ...","[Nearctic, Palearctic, Indomalayan, Afrotro...","[pack, route, rout]","[Carnivore, , Scavenger]",[Greenland],"[Terrestrial, Cursorial, Altricial, Pack hu...",NaN
1,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,"2,154-3,159",10-15 yrs,96 km/h,65-306 kg,NaN,200-390 cm,NaN,NaN,NaN,"[Forest, Rainforest, Montane forest, Riparian,...","[Tropical, Temperate]",Not a migrant,NaN,NaN,Polygyny,November-April,103 days,1-7 cubs,18 mos-3 yrs,NaN,NaN,cub,NaN,Decreasing,Endangered (EN),"[Nocturnal, Carnivore, Cursorial, Terrestrial,...",[Asia],"[South Asia, Southeast Asia, East Asia]","[Bangladesh, Bhutan, China, India, Indon...",[Thailand],"[Palearctic, Indomalayan]",NaN,[Carnivore],"[Tibet, Yunnan]","[Cursorial, Terrestrial, Ambush predator, A...",NaN
2,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,"200,000",20-50 yrs,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,NaN,NaN,NaN,"[Forest, Woodland]","[Temperate, Cold, Polar]","Hibernating, Migrating",NaN,NaN,"Polygynandry,",May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC),"[Crepuscular, Omnivore, Terrestrial, Altricial...","[Asia, Europe, North America]","[South Asia, Western Asia, East Asia, Centr...","[Albania, Armenia, Austria, Azerbaijan, Be...",NaN,"[Nearctic, Palearctic, Indomalayan]","[sloth, sleuth]",[Omnivore],"[Estonia, Finland, France, Georgia, Greece...","[Terrestrial, Altricial, Nomadic, Territori...",NaN
3,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,10-25 Thou,80-90 yrs,20 km/h,100-160 t,NaN,25-30 m,NaN,NaN,NaN,"[Oceanic pelagic zone, Marine, Neritic zone]","[Tropical, Temperate, Cold, Polar]",Migrating,NaN,NaN,Monogamy,winter or early spring,1 year,1 calf,8 months,cow,bull,calf,NaN,Increasing,Endangered (EN),"[Carnivore, Piscivores, Aquatic, Precocial, Na...","[Africa, South America, Oceania, North Amer...","[Sub-Saharan Africa, Caribbean Islands, Sout...","[Angola, Argentina, Australia, Bahamas, Ba...","[Chile, China, Colombia, Comoros, Costa Ri...",NaN,"[pod, gam, herd, school, mod]","[Carnivore, , Piscivores]","[Atlantic Ocean, Pacific Ocean]","[Aquatic, Precocial, Natatorial, Viviparous...","[Greenland, Kamchatka]"
4,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,"50,000",30-100 yrs,45 km/h,3-6 t,NaN,6-9 m,NaN,NaN,NaN,"[Oceanic pelagic zone, Marine, Neritic zone, E...","[Tropical, Temperate, Cold, Polar]",Partial Migrant,NaN,NaN,Polygynandry,"year-round, usually in summer",15-18 months,1 calf,2 years,cow,bull,calf,NaN,NaN,NaN,"[Diurnal, Carnivore, Aquatic, Precocial, Cosmo...","[Africa, Oceania, Antarctica, North America...","[North Africa, Caribbean Islands, South Asia...","[Algeria, Antigua and Barbuda, Argentina, A...","[Brunei, Cambodia, Cameroon, Canada, Cape ...",NaN,"[pod, gam, herd, school, mod]",[Carnivore],"[Arctic Ocean, Atlantic Ocean, Pacific Ocean]","[Aquatic, Precocial, Cosmopolitan, Natatori...","[Newfoundland, Hawaii, Greenland]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3232,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Icteridae,Amblycercus,Amblycercus holosericeus,NaN,NaN,NaN,56.7-70.9 g,NaN,21.6-25.4 cm,NaN,NaN,NaN,[Forest],[Tropical],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Least concern (LC),"[Diurnal, Omnivore, Zoochory, Terrestrial, Mon...","[South America, North America]",NaN,"[Belize, Costa Rica, El Salvador, Guatemala...",NaN,NaN,NaN,NaN,"[Colombia, Peru, Venezuela]",NaN,NaN
3233,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Icteridae,Icterus,Icterus laudabilis,NaN,NaN,NaN,36.9 g,NaN,20-22 cm,NaN,NaN,NaN,"[Agricultural, Anthropogenic biome, Forest, Mo...",[Tropical],Not a migrant,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Endangered (EN),"[Diurnal, Herbivore, Frugivore, Nectarivore, A...",[North America],NaN,[Saint Lucia],NaN,NaN,NaN,"[Herbivore, , Frugivore, , Nectarivore]",[Neotropical],"[Arboreal, Zoochory, Island endemic, Terres...",NaN
3234,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Muscicapidae,Swynnertonia,Swynnertonia swynnertoni,NaN,NaN,NaN,NaN,NaN,12-13 cm,NaN,NaN,NaN,"[Forest, Mountains]",[Tropical],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Vulnerable (VU),"[Diurnal, Carnivore, Insectivores, Terrestrial...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3235,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Tyrannidae,Mionectes,Mionectes oleagineus,NaN,NaN,NaN,13 g,NaN,NaN,NaN,NaN,NaN,"[Forest, Rainforest, Grassland, Freshwater, An...",[],Not a migrant,NaN,Your browser does not support the audio element.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,Least concern (LC),"[Terrestrial, Not a migrant, starts with]","[South America, North America]",NaN,"[Trinidad and Tobago, Belize, Costa Rica, E...","[Bolivia, Brazil, Colombia, Guyana, Peru, ...",NaN,NaN,NaN,[French Guiana],"[Terrestrial, ]",NaN
3236,Animalia,Chordata,NaN,Aves,Procellariiformes,NaN,Procellariidae,Pelecanoides,Pelecanoides magellani,NaN,NaN,NaN,145-174 g,NaN,19 cm,NaN,NaN,NaN,"[Coastal, Neritic zone, Oceanic pelagic zone, ...",[Temperate],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Least concern (LC),"[Diurnal, Nocturnal, Carnivore, Piscivores, Te...",[South America],NaN,"[Chile, Argentina]",[Falkland Islands],NaN,NaN,NaN,[Neotropical],NaN,"[Atlantic Ocean, Pacific Ocean]"

In [16]:
df_split_animals_info.to_csv('animals_split_info.csv')