# Khám phá dữ liệu

Notebook này để khám phá dữ liệu.

## Import những thư viện cần thiết

In [1]:
import numpy as np
import pandas as pd

## Đọc dữ liệu từ file

File dữ liệu của đồ án sau bước thu thập dữ liệu đang nằm tại địa chỉ '../thu_thap_du_lieu/animal_crawler/animal_info.csv'. Ta sẽ tiến hành đọc dữ liệu đã thu thập và lưu vào DataFrame `animal_df`

In [2]:
animal_df = pd.read_csv('../thu_thap_du_lieu/animal_crawler/animals_info.csv')

Hiển thị 5 dòng đầu tiên trong dữ liệu để xem thử đã đọc đúng hay chưa

In [3]:
pd.reset_option('display.max_colwidth')
animal_df.head(5)

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Top speed,Weight,Height,Length,Attributes,Distribution,Habits,Diet,Mating_Habits,Population
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,...,75 km/h,16-60 kg,80-85 cm,105-160 cm,"Nocturnal,Carnivore,Scavenger,Terrestrial,Curs...","{'Geography': {'Continents': 'Asia, Europe, No...","{'Group name': 'pack, route, rout', 'Lifestyle...","Carnivore,,Scavenger","{'Mating behavior': 'Monogamy', 'Reproduction ...","{'Population trend': 'Stable', 'Population sta..."
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,...,96 km/h,65-306 kg,NaN,200-390 cm,"Nocturnal,Carnivore,Cursorial,Terrestrial,Ambu...","{'Geography': {'Continents': 'Asia', 'Subconti...","{'Lifestyle': 'Cursorial, Terrestrial, Ambush ...",Carnivore,"{'Mating behavior': 'Polygyny', 'Reproduction ...","{'Population trend': 'Decreasing', 'Population..."
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,...,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,"Crepuscular,Omnivore,Terrestrial,Altricial,Nom...","{'Geography': {'Continents': 'Asia, Europe, No...","{'Group name': 'sloth, sleuth', 'Lifestyle': '...",Omnivore,"{'Mating behavior': 'Polygynandry,', 'Reproduc...","{'Population trend': 'Stable', 'Population sta..."
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,...,20 km/h,100-160 t,NaN,25-30 m,"Carnivore,Piscivores,Aquatic,Precocial,Natator...","{'Geography': {'Continents': 'Africa, South Am...","{'Group name': 'pod, gam, herd, school, mod', ...","Carnivore,,Piscivores","{'Mating behavior': 'Monogamy', 'Reproduction ...","{'Population trend': 'Increasing', 'Population..."
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,...,45 km/h,3-6 t,NaN,6-9 m,"Diurnal,Carnivore,Aquatic,Precocial,Cosmopolit...","{'Geography': {'Continents': 'Africa, Oceania,...","{'Group name': 'pod, gam, herd, school, mod', ...",Carnivore,"{'Mating behavior': 'Polygynandry', 'Reproduct...",{'Population status': 'Data deficient (DD)'}

Xem xét dữ liệu trên thì thấy một số dòng bị lỗi, cần loại bỏ.
Cụ thể ở đây là thu thập dữ liệu về thú nhưng có một số dòng có giá trị cột 'Kingdom' không phải là 'Animalia'. Ở đây ta sẽ xóa luôn những dòng như thế, vì dữ liệu khá lớn nên xóa bớt một vài dòng có lẽ sẽ không có ảnh hưởng nhiều.

In [4]:
animal_df = animal_df[animal_df['Kingdom'] == 'Animalia']

## Dữ liệu có bao nhiêu dòng, bao nhiêu cột?

In [5]:
animal_df.shape

(28525, 22)

## Mỗi dòng có ý nghĩa gì? Có vấn đề các dòng có ý nghĩa khác nhau không?

Mỗi dòng cho chúng ta biết các thông tin về một con vật, tất cả các dòng đều có cùng ý nghĩa như nhau.

## Dữ liệu có các dòng bị lặp không?

Chúng ta sử dụng hàm 'duplicated' trong pandas để kiểm tra dòng đó có phải bị lặp trong DataFrame hay không. Nếu kết quả là dòng đó bị lặp sẽ trả về giá trị 1, ngược lại sẽ là 0. Kế tiếp chúng ta sử dùng hàm 'sum' để tính tất cả giá trị trả về của hàm 'duplicated'. Nếu kết quả > 0 thì chứng tỏ có tồn tại dòng bị lặp.

In [6]:
animal_df.duplicated().sum()

0

Vậy là dữ liệu của chúng ta không tồn lại dòng nào bị lặp lại.

## Mỗi cột có ý nghĩa gì?

Sau khi thu thập dữ liệu xong, nhóm em đã tự phân tích ý nghĩa của mỗi trong file dữ liệu vừa thu thập, sau đó viết vào file `col_meaning.xlsx`. Đọc file excel này để biết được ý nghĩa của mỗi cột.

In [7]:
xlsx = pd.ExcelFile('col_meaning.xlsx')
col_meaning_df =pd.read_excel(xlsx,"Sheet1")
pd.set_option('display.max_colwidth', 0)
col_meaning_df

,Column,Description
0,Name,Name of Animal
1,Kingdom,Giới là đơn vị phân loại lớn nhất bao gồm các ngành sinh vật có chung những đặc điểm nhất định.
2,Phylum,Ngành: Một đơn vị phân loại ở cấp dưới giới và trên lớp.
3,Subphylum,Phân Ngành: là một bậc phân loại nằm trung gian giữa ngành và lớp hoặc phân thứ ngành hoặc liên lớp
4,Class,Lớp: Một mức độ phân loại động vật trong một ngành. Các lớp sau đó được chia nhỏ thành các nhóm khác được gọi là bộ
5,Order,Bộ: là một cấp nằm giữa lớp và họ.
6,Suborder,"Phân bộ: một nhóm thực vật hoặc động vật có liên quan, có quan hệ gần gũi hơn so với một bộ nhưng ít giống nhau hơn so với một họ."
7,Family,"Họ: Bộ được chia thành các họ, họ sẽ được chia thành các chi"
8,Genus,Chi: còn gọi là giống là một đơn vị phân loại sinh học dùng để chỉ một hoặc một nhóm loài có kiểu hình tương tự và mối quan hệ tiến hóa gần gũi với nhau.
9,Species,Loài: là một nhóm các cá thể sinh vật có những đặc điểm sinh học tương đối giống nhau và có khả năng giao phối với nhau và sinh sản ra thế hệ tương lai.
10,Population size,Ước tính số cá thể đang sống của loài
11,Life span,Tuổi thọ
12,Top speed,Tốc độ
13,Weight,Cân nặng
14,Height,Chiều cao
15,Length,Chiều dài
16,Attributes,Một số thông tin chính về loài vật
17,Distribution,Phân bổ: Nơi sinh sống
18,Habits,Thói quen
19,Diet,"Chế độ ăn (ăn cỏ, ăn tạp,…)"
20,Mating_Habits,Thói quen giao phối
21,Population,"Bao gồm xu hướng dân số (tăng, giảm, ổn định) và trạng thái dân số (nguy cấp, bị đe dọa, ít quan tâm,…)"

## Các cột lúc này đang có kiểu dữ liệu gì?

In [8]:
animal_df.dtypes

Name               object
Kingdom            object
Phylum             object
Subphylum          object
Class              object
Order              object
Suborder           object
Family             object
Genus              object
Species            object
Population size    object
Life span          object
Top speed          object
Weight             object
Height             object
Length             object
Attributes         object
Distribution       object
Habits             object
Diet               object
Mating_Habits      object
Population         object
dtype: object

## Tính xem tình trạng của mỗi cột dữ liệu hiện tại như thế nào?

### Với mỗi cột ta sẽ tính:
- Tỉ lệ mất mát: missing_ratio
- Số lượng giá trị khác nhau: num_values
- Số lần xuất hiện của từng giá trị: value

Viết hàm "col_info" để tính và lưu kết quả vào mảng "cat_col_info_df"

In [9]:
def col_info(col, array):
    temp = pd.DataFrame(array[col])
    temp = temp.dropna()
    temp = np.array(temp[col])
    data = []
    # missing_ratio
    data.append(round((100 - (len(temp) / len(array[col]) * 100)), 1))
    # num_values
    temp = np.unique(temp, return_counts=True)
    data.append(len(temp[0]))
    # value
    temp = pd.Series(data = temp[1], index = temp[0])
    data.append(temp)
    # num_values
    return data

In [10]:
cat_col_info_df = pd.DataFrame(index = ['missing_ratio', 'num_values', 'value'])
for i in animal_df.columns:
    if animal_df[i].dtype not in [float, int]:
        cat_col_info_df[i] = col_info(i, animal_df)
        
pd.reset_option('display.max_colwidth')
cat_col_info_df

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,...,Top speed,Weight,Height,Length,Attributes,Distribution,Habits,Diet,Mating_Habits,Population
missing_ratio,0.0,0.0,0.0,64.4,0.0,1.5,91.0,0.0,0.0,0.0,...,98.0,90.0,98.9,89.7,0.0,0.0,0.0,90.9,0.0,0.0
num_values,28525,1,2,1,10,118,13,840,6127,28523,...,124,2232,245,2101,3078,8335,2143,308,2682,40
value,? Nycticebus linglom 1 AEECL's sportive l...,Animalia 28525 dtype: int64,Chordata 23659 Mollusca 4866 dtype: int64,Vertebrata 10152 dtype: int64,Amphibia 3393 Aves 1011...,Accipitriformes 255 Adapedonta 10 ...,Alcedini 109 Caniformia 19...,Abrocomidae 10 Abronicidae ...,Aaadonta 6 Abditomys 1 Abeillia ...,"""Calamita"" melanorabdotus 1 ""Calamita...",...,0.24 km/h 1 0.26 km/h 1 0.27 km/h 1 0...,0-0 kg 3 0.010-0.796 g 1 0.02-2...,0.5 m 1 0.7-1.3 m 1 0.75-1 m ...,0.5 m 2 0.5-1.8 m 1 0.6-2.43 m ...,"Algivore,Detritivore,Herbivore,Fossorial,Polyg...",{'Geography': {'Biogeographical realms': 'Aust...,"{'Group name': '""bind"", contradiction, fling, ...","Algivore,,Detritivore,,Herbivore ...",{'Baby carrying': '1 baby'} ...,{'Population status': 'Critically endangered (...

## Xử lý tách các cột có kiểu dictionary thành nhiều cột

Đầu tiên các cột dictionary đều có kiểu là string nên ta phải xử lý chuyển các cột trên thành dict

In [11]:
for i in animal_df:
    if animal_df[i][0].find('{') != -1:
        animal_df[i] = animal_df[i].apply(eval)

Viết hàm "split_col" để split các cột có kiểu dữ liệu là dict thành nhiều cột

In [52]:
def split_col(df):
    df_split_animals_info = pd.DataFrame()
    for col in df.columns:
        if type(df[col][0]) == dict:
            df_split_animals_info = pd.concat([df_split_animals_info, df[col].apply(pd.Series, dtype = object)], axis = 1)
        else:
            df_col = pd.DataFrame(df[col])
            df_split_animals_info = pd.concat([df_split_animals_info, df_col], axis = 1)
    return df_split_animals_info

In [47]:
df_split_animals_info = pd.DataFrame()
a= pd.DataFrame(animal_df['Name'])
df_split_animals_info = pd.concat([df_split_animals_info, a], axis = 1)
df_split_animals_info = pd.concat([df_split_animals_info, a], axis = 1)
df_split_animals_info

                              Name                         Name
0                        Grey Wolf                    Grey Wolf
1                            Tiger                        Tiger
2                       Brown Bear                   Brown Bear
3                       Blue Whale                   Blue Whale
4                     Killer Whale                 Killer Whale
...                            ...                          ...
29350            Córdoba cinclodes            Córdoba cinclodes
29351          Western hemispingus          Western hemispingus
29352  Sulphur-bearded reedhaunter  Sulphur-bearded reedhaunter
29355        McConnell's spinetail        McConnell's spinetail
29356              Junín canastero              Junín canastero

[28525 rows x 2 columns]

In [48]:
df_split_animals_info = split_col(animal_df)
pd.set_option('display.max_columns', None)
df_split_animals_info

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,Population size,Life span,Top speed,Weight,Height,Length,Attributes,Geography,Biome,Climate,Group name,Lifestyle,Seasonal behavior,Predators,Bird's call,Diet,Mating behavior,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,"400,000",10-20 yrs,75 km/h,16-60 kg,80-85 cm,105-160 cm,"Nocturnal,Carnivore,Scavenger,Terrestrial,Curs...","{'Continents': 'Asia, Europe, North America, A...","[Wetlands , Shrubland, Forest, Mountains, Anth...","[Temperate, Cold, Polar, Tropical]","pack, route, rout","Terrestrial, Cursorial, Altricial, Pack hunter...",Not a migrant,NaN,NaN,"Carnivore,,Scavenger",Monogamy,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC)
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,"2,154-3,159",10-15 yrs,96 km/h,65-306 kg,NaN,200-390 cm,"Nocturnal,Carnivore,Cursorial,Terrestrial,Ambu...","{'Continents': 'Asia', 'Subcontinents': 'South...","[Forest, Rainforest, Montane forest, Riparian,...","[Tropical, Temperate]",NaN,"Cursorial, Terrestrial, Ambush predator, Altri...",Not a migrant,NaN,NaN,Carnivore,Polygyny,November-April,103 days,1-7 cubs,18 mos-3 yrs,NaN,NaN,cub,NaN,Decreasing,Endangered (EN)
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,"200,000",20-50 yrs,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,"Crepuscular,Omnivore,Terrestrial,Altricial,Nom...","{'Continents': 'Asia, Europe, North America', ...","[Forest, Woodland]","[Temperate, Cold, Polar]","sloth, sleuth","Terrestrial, Altricial, Nomadic, Territorial, ...","Hibernating, Migrating",NaN,NaN,Omnivore,"Polygynandry,",May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC)
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,10-25 Thou,80-90 yrs,20 km/h,100-160 t,NaN,25-30 m,"Carnivore,Piscivores,Aquatic,Precocial,Natator...","{'Continents': 'Africa, South America, Oceania...","[Oceanic pelagic zone, Marine, Neritic zone]","[Tropical, Temperate, Cold, Polar]","pod, gam, herd, school, mod","Aquatic, Precocial, Natatorial, Viviparous, Co...",Migrating,NaN,NaN,"Carnivore,,Piscivores",Monogamy,winter or early spring,1 year,1 calf,8 months,cow,bull,calf,NaN,Increasing,Endangered (EN)
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,"50,000",30-100 yrs,45 km/h,3-6 t,NaN,6-9 m,"Diurnal,Carnivore,Aquatic,Precocial,Cosmopolit...","{'Continents': 'Africa, Oceania, Antarctica, N...","[Oceanic pelagic zone, Marine, Neritic zone, E...","[Tropical, Temperate, Cold, Polar]","pod, gam, herd, school, mod","Aquatic, Precocial, Cosmopolitan, Natatorial, ...",Partial Migrant,NaN,NaN,Carnivore,Polygynandry,"year-round, usually in summer",15-18 months,1 calf,2 years,cow,bull,calf,NaN,NaN,Data deficient (DD)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29350,Córdoba cinclodes,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Cinclodes,Cinclodes comechingonus,NaN,NaN,NaN,NaN,NaN,NaN,"Terrestrial,Migrating,starts with","{'Continents': 'South America', 'Countries': '...","[Grassland, Rocky areas ]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Least concern (LC)
29351,Western hemispingus,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Thraupidae,Sphenopsis,Sphenopsis ochracea,NaN,NaN,NaN,NaN,NaN,NaN,"Terrestrial,Not a migrant,starts with","{'Continents': 'South America', 'Countries': '...",[Forest],[],NaN,"Terrestrial,",Not a migrant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,Least concern (LC)
29352,Sulphur-bearded reedhaunter,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Cranioleuca,Limnoctites sulphuriferus,NaN,NaN,NaN,NaN,NaN,NaN,"Terrestrial,Migrating,starts with","{'Continents': 'South America', 'Countries': '...","[Freshwater, Shrubland, Wetlands ]",[],NaN,"Terrestrial,",Migrating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Least concern (LC)
29355,McConnell's spinetail,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Synallaxis,Synallaxis macconnelli,NaN,NaN,NaN,NaN,NaN,NaN,"Terrestrial,Not a migrant,starts with","{'Continents': 'South America', 'Countries': '...","[Anthropogenic biome, Forest]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,Least concern (LC)
29356,Junín canastero,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Asthenes,Asthenes virgata,NaN,NaN,NaN,NaN,NaN,NaN,"Terrestrial,Not a migrant,starts with","{'Continents': 'South America', 'Countries': '...","[Grassland, Shrubland]",[],NaN,"Terrestrial,",Not a migrant,NaN,Your browser does not support the audio element.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Least concern (LC)

Sau khi split dữ liệu có số dòng là 28525 và số cột là 37, tăng lên 15 cột

Nhưng nhìn lại dữ liệu vẫn còn cột là dictionary như "Geograpy", như vậy ta phải split thêm 1 lần nữa

In [53]:
df_split_animals_info = split_col(df_split_animals_info)
df_split_animals_info.head(100)

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,Population size,Life span,Top speed,Weight,Height,Length,Attributes,Continents,Subcontinents,Countries,Regions,Biogeographical realms,Wwf biomes,Oceans,Introduced countries,Seas,Islands,Biome,Climate,Group name,Lifestyle,Seasonal behavior,Predators,Bird's call,Diet,Mating behavior,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,"400,000",10-20 yrs,75 km/h,16-60 kg,80-85 cm,105-160 cm,"Nocturnal,Carnivore,Scavenger,Terrestrial,Curs...","Asia, Europe, North America, Africa","South Asia, Western Asia, Southeast Asia, East...","Albania, Armenia, Azerbaijan, Belarus, Bhutan,...","Czech Republic, Estonia, Finland, France, Geor...",Greenland,"Nearctic, Palearctic, Indomalayan, Afrotropical",NaN,NaN,NaN,NaN,"[Wetlands , Shrubland, Forest, Mountains, Anth...","[Temperate, Cold, Polar, Tropical]","pack, route, rout","Terrestrial, Cursorial, Altricial, Pack hunter...",Not a migrant,NaN,NaN,"Carnivore,,Scavenger",Monogamy,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC)
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,"2,154-3,159",10-15 yrs,96 km/h,65-306 kg,NaN,200-390 cm,"Nocturnal,Carnivore,Cursorial,Terrestrial,Ambu...",Asia,"South Asia, Southeast Asia, East Asia","Bangladesh, Bhutan, China, India, Indonesia,...",Thailand,"Tibet, Yunnan","Palearctic, Indomalayan",NaN,NaN,NaN,NaN,"[Forest, Rainforest, Montane forest, Riparian,...","[Tropical, Temperate]",NaN,"Cursorial, Terrestrial, Ambush predator, Altri...",Not a migrant,NaN,NaN,Carnivore,Polygyny,November-April,103 days,1-7 cubs,18 mos-3 yrs,NaN,NaN,cub,NaN,Decreasing,Endangered (EN)
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,"200,000",20-50 yrs,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,"Crepuscular,Omnivore,Terrestrial,Altricial,Nom...","Asia, Europe, North America","South Asia, Western Asia, East Asia, Central A...","Albania, Armenia, Austria, Azerbaijan, Belarus...",NaN,"Estonia, Finland, France, Georgia, Greece, Ind...","Nearctic, Palearctic, Indomalayan",NaN,NaN,NaN,NaN,"[Forest, Woodland]","[Temperate, Cold, Polar]","sloth, sleuth","Terrestrial, Altricial, Nomadic, Territorial, ...","Hibernating, Migrating",NaN,NaN,Omnivore,"Polygynandry,",May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC)
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,10-25 Thou,80-90 yrs,20 km/h,100-160 t,NaN,25-30 m,"Carnivore,Piscivores,Aquatic,Precocial,Natator...","Africa, South America, Oceania, North America,...","Sub-Saharan Africa, Caribbean Islands, South A...","Angola, Argentina, Australia, Bahamas, Banglad...","Chile, China, Colombia, Comoros, Costa Rica, C...","Atlantic Ocean, Pacific Ocean",NaN,"Greenland, Kamchatka",NaN,NaN,NaN,"[Oceanic pelagic zone, Marine, Neritic zone]","[Tropical, Temperate, Cold, Polar]","pod, gam, herd, school, mod","Aquatic, Precocial, Natatorial, Viviparous, Co...",Migrating,NaN,NaN,"Carnivore,,Piscivores",Monogamy,winter or early spring,1 year,1 calf,8 months,cow,bull,calf,NaN,Increasing,Endangered (EN)
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,"50,000",30-100 yrs,45 km/h,3-6 t,NaN,6-9 m,"Diurnal,Carnivore,Aquatic,Precocial,Cosmopolit...","Africa, Oceania, Antarctica, North America, So...","North Africa, Caribbean Islands, South Asia, C...","Algeria, Antigua and Barbuda, Argentina, Austr...","Brunei, Cambodia, Cameroon, Canada, Cape Verde...","Arctic Ocean, Atlantic Ocean, Pacific Ocean",NaN,"Newfoundland, Hawaii, Greenland",NaN,NaN,NaN,"[Oceanic pelagic zone, Marine, Neritic zone, E...","[Tropical, Temperate, Cold, Polar]","pod, gam, herd, school, mod","Aquatic, Precocial, Cosmopolitan, Natatorial, ...",Partial Migrant,NaN,NaN,Carnivore,Polygynandry,"year-round, usually in summer",15-18 months,1 calf,2 years,cow,bull,calf,NaN,NaN,Data deficient (DD)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,Black Rhinoceros,Animalia,Chordata,Vertebrata,Mammalia,Perissodactyla,NaN,Rhinocerotidae,Diceros,Diceros bicornis,"4,880-5,000",30-49 yrs,42-58 km/h,"800-1,400 kg",140-180 cm,3-3.8 m,"Diurnal,Herbivore,Folivore,Lignivore,Terrestri...",Africa,Sub-Saharan Africa,"Angola, Kenya, Mozambique, Namibia, South Afri...",NaN,"Swaziland, Zambia",Afrotropical,NaN,NaN,NaN,NaN,"[Shrubland, Savanna, Woodland]","[Tropical, Arid, Temperate]","crash, stubbornness","Terrestrial, Precocial, Browsing, Zoochory, Te...",Not a migrant,NaN,NaN,"Herbivore,,Folivore,,Lignivore",Polygyny,year-round,15 months,1 calf,4 years,cow,bull,calf,NaN,Increasing,Critically endangered (CR)
107,Markhor,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Bovidae,Capra,Capra falconeri,"5,754",10-13 yrs,17 km/h,32-110 kg,65-115 cm,132-186 cm,"Diurnal,Herbivore,Folivore,Graminivore,Terrest...",Asia,"Central Asia, South Asia","Afghanistan, India, Pakistan, Tajikistan, Turk...",NaN,"Palearctic, Indomalayan","Temperate broadleaf and mixed forest, Temperat...",NaN,NaN,NaN,NaN,"[Rocky areas , Forest, Mountains, Shrubland, W...","[Tropical, Temperate]","tribe, trip, drove, herd, flock, trippe","Terrestrial, Precocial, Grazing, Browsing, Zoo...",Altitudinal Migrant,NaN,NaN,"Herbivore,,Folivore,,Graminivore",Polygyny,winter,135-170 days,1-2 kids,6 months,"doe, nanny","buck, billy","kid, billy",NaN,Increasing,Near Threatened (NT)
109,Eurasian Lynx,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Lynx,Lynx lynx,70-80 Thou,13-25 yrs,80 km/h,8-30 kg,60-75 cm,80-130 cm,"Crepuscular,Nocturnal,Carnivore,Terrestrial,Te...","Asia, Europe","South Asia, Western Asia, East Asia, Central Asia","Albania, Armenia, Austria, Azerbaijan, Belarus...",NaN,"Estonia, Finland, France, Georgia, Germany, Hu...","Palearctic, Indomalayan",NaN,NaN,NaN,NaN,"[Forest, Mountains, Shrubland, Grassland, Rock...","[Cold, Temperate]","destruction (wild cats), clowder, clutter, pounce","Terrestrial, Territorial, Viviparous, Ambush p...",Not a migrant,NaN,NaN,Carnivore,Polygyny,February-April,2 months,2-3 kittens,10 months,NaN,NaN,kitten,NaN,Stable,Least concern (LC)
110,Dromedary Camel,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Camelidae,Camelus,Camelus dromedarius,NaN,40-50 yrs,64 km/h,300-600 kg,1.7-2 m,2-3 m,"Diurnal,Herbivore,Folivore,Graminivore,Terrest...","Africa, Asia","North Africa, Sub-Saharan Africa, Western Asia...",NaN,"New South Wales, South Australia, Western Aus...","Australasian, Afrotropical, Palearctic","Desert and Xeric Shrublands, Tropical savanna",NaN,NaN,NaN,NaN,"[Grassland, Anthropogenic biome, Agricultural,...","[Arid, Tropical, Temperate]","caravan, train, herd, flock","Terrestrial, Precocial, Cursorial, Grazing, Br...",Not a migrant,NaN,NaN,"Herbivore,,Folivore,,Graminivore",Polygyny,November-March,13 months,1-2 calves,1-2 years,cow,bull,calf,NaN,NaN,Not evaluated (NE)
114,Common Warthog,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Suidae,Phacochoerus,Phacochoerus africanus,Unknown,12-18 yrs,NaN,45-150 kg,63.5-85 cm,0.9-1.5 m,"Diurnal,Omnivore,Scavenger,Terrestrial,Altrici...",Africa,Sub-Saharan Africa,"Angola, Benin, Botswana, Burkina Faso, Burundi...",NaN,"Djibouti, Eritrea, Ethiopia, Gabon, Gambia, Gh...",Afrotropical,NaN,NaN,NaN,NaN,"[Agricultural, Anthropogenic biome, Grassland,...",[Tropical],"drift, drove, sounder, team, herd","Terrestrial, Altricial, Burrowing, Grazing, Vi...",Not a migrant,NaN,NaN,"Omnivore,,Scavenger",Polygynandry,starts in late rainy or early dry season,5-6 months,2-8 piglets,6 months,sow,boar,"piglet, shoat",NaN,Decreasing,Least concern (LC)

Sau khi split dữ liệu tăng thêm 9 cột

Lúc này ta tính lại missing_ratio xem các cột sau khi split như thế nào nhé

In [54]:
cat_col_info_df = pd.DataFrame(index = ['missing_ratio', 'num_values', 'value'])
for i in df_split_animals_info.columns:
    if df_split_animals_info[i].dtype not in [float, int]:
        cat_col_info_df[i] = col_info(i, df_split_animals_info)

cat_col_info_df

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,Population size,Life span,Top speed,Weight,Height,Length,Attributes,Continents,Subcontinents,Countries,Regions,Biogeographical realms,Wwf biomes,Oceans,Introduced countries,Seas,Islands,Biome,Climate,Group name,Lifestyle,Seasonal behavior,Predators,Bird's call,Diet,Mating behavior,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
missing_ratio,0.0,0.0,0.0,64.4,0.0,1.5,91.0,0.0,0.0,0.0,93.7,93.6,98.0,90.0,98.9,89.7,0.0,26.2,95.8,52.4,90.4,66.9,92.4,99.4,99.1,99.9,98.7,0.0,0.0,94.7,64.0,71.6,100.0,81.5,90.9,92.6,94.4,94.5,90.8,93.6,96.1,96.1,93.6,97.4,21.7,18.8
num_values,28525,1,2,1,10,118,13,840,6127,28523,638,581,124,2232,245,2101,3078,269,245,3361,1020,1243,435,82,214,11,147,2606,50,238,1508,49,2,2,308,27,655,758,715,582,34,39,85,340,4,9
value,? Nycticebus linglom 1 AEECL's sportive l...,Animalia 28525 dtype: int64,Chordata 23659 Mollusca 4866 dtype: int64,Vertebrata 10152 dtype: int64,Amphibia 3393 Aves 1011...,Accipitriformes 255 Adapedonta 10 ...,Alcedini 109 Caniformia 19...,Abrocomidae 10 Abronicidae ...,Aaadonta 6 Abditomys 1 Abeillia ...,"""Calamita"" melanorabdotus 1 ""Calamita...","0.45-1 M 1 1 Mln 2 1,000 ...",1 yr 2 1-10 yrs 2 1-12.5 yrs...,0.24 km/h 1 0.26 km/h 1 0.27 km/h 1 0...,0-0 kg 3 0.010-0.796 g 1 0.02-2...,0.5 m 1 0.7-1.3 m 1 0.75-1 m ...,0.5 m 2 0.5-1.8 m 1 0.6-2.43 m ...,"Algivore,Detritivore,Herbivore,Fossorial,Polyg...",...,"Angola, Benin, Botswana, Burkina Faso, Burundi...",...,...,...,...,...,...,"Arctic Ocean, Atlantic Ocean, Pacific Ocean ...",...,[] ...,[] 25...,"""bind"", contradiction, fling, hill, ""time-step...",...,...,Arctic Wolf 1 Common Ringtail Po...,...,"Algivore,,Detritivore,,Herbivore ...",1 1 1.8 ...,26-35 days ...,0 to 0.01 months 1 1 ...,0 to 1 2 0 to 2 ...,&gt;2 weeks 1 0 days ...,angeline 1 bitch ...,billy 2 boar 8...,"Fawn, twins 1 Hatchling 1 In...",1 month 13 1-3 months 1 1.5 months...,Decreasing 8381 Increasing 782 Stable ...,Critically endangered (CR) 931 Data defic...

## Tiếp tục tiền xử lý dữ liệu nhé

### Loại bỏ một số cột không cần thiết

Sau khi tách các cột thành dictionary, đã xuất hiện một số cột không cần thiết mà tỷ lệ miss lại khá cao, ta cần vứt bỏ những cột này cho dễ xử lý về sau.

In [55]:
cols = ['Oceans', 'Introduced countries', 'Seas', 'Islands', 'Predators', "Bird's call"]
for col in cols:
    df_split_animals_info  = df_split_animals_info.drop(columns  = col)
df_split_animals_info

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,Population size,Life span,Top speed,Weight,Height,Length,Attributes,Continents,Subcontinents,Countries,Regions,Biogeographical realms,Wwf biomes,Biome,Climate,Group name,Lifestyle,Seasonal behavior,Diet,Mating behavior,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,"400,000",10-20 yrs,75 km/h,16-60 kg,80-85 cm,105-160 cm,"Nocturnal,Carnivore,Scavenger,Terrestrial,Curs...","Asia, Europe, North America, Africa","South Asia, Western Asia, Southeast Asia, East...","Albania, Armenia, Azerbaijan, Belarus, Bhutan,...","Czech Republic, Estonia, Finland, France, Geor...",Greenland,"Nearctic, Palearctic, Indomalayan, Afrotropical","[Wetlands , Shrubland, Forest, Mountains, Anth...","[Temperate, Cold, Polar, Tropical]","pack, route, rout","Terrestrial, Cursorial, Altricial, Pack hunter...",Not a migrant,"Carnivore,,Scavenger",Monogamy,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC)
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,"2,154-3,159",10-15 yrs,96 km/h,65-306 kg,NaN,200-390 cm,"Nocturnal,Carnivore,Cursorial,Terrestrial,Ambu...",Asia,"South Asia, Southeast Asia, East Asia","Bangladesh, Bhutan, China, India, Indonesia,...",Thailand,"Tibet, Yunnan","Palearctic, Indomalayan","[Forest, Rainforest, Montane forest, Riparian,...","[Tropical, Temperate]",NaN,"Cursorial, Terrestrial, Ambush predator, Altri...",Not a migrant,Carnivore,Polygyny,November-April,103 days,1-7 cubs,18 mos-3 yrs,NaN,NaN,cub,NaN,Decreasing,Endangered (EN)
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,"200,000",20-50 yrs,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,"Crepuscular,Omnivore,Terrestrial,Altricial,Nom...","Asia, Europe, North America","South Asia, Western Asia, East Asia, Central A...","Albania, Armenia, Austria, Azerbaijan, Belarus...",NaN,"Estonia, Finland, France, Georgia, Greece, Ind...","Nearctic, Palearctic, Indomalayan","[Forest, Woodland]","[Temperate, Cold, Polar]","sloth, sleuth","Terrestrial, Altricial, Nomadic, Territorial, ...","Hibernating, Migrating",Omnivore,"Polygynandry,",May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC)
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,10-25 Thou,80-90 yrs,20 km/h,100-160 t,NaN,25-30 m,"Carnivore,Piscivores,Aquatic,Precocial,Natator...","Africa, South America, Oceania, North America,...","Sub-Saharan Africa, Caribbean Islands, South A...","Angola, Argentina, Australia, Bahamas, Banglad...","Chile, China, Colombia, Comoros, Costa Rica, C...","Atlantic Ocean, Pacific Ocean",NaN,"[Oceanic pelagic zone, Marine, Neritic zone]","[Tropical, Temperate, Cold, Polar]","pod, gam, herd, school, mod","Aquatic, Precocial, Natatorial, Viviparous, Co...",Migrating,"Carnivore,,Piscivores",Monogamy,winter or early spring,1 year,1 calf,8 months,cow,bull,calf,NaN,Increasing,Endangered (EN)
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,"50,000",30-100 yrs,45 km/h,3-6 t,NaN,6-9 m,"Diurnal,Carnivore,Aquatic,Precocial,Cosmopolit...","Africa, Oceania, Antarctica, North America, So...","North Africa, Caribbean Islands, South Asia, C...","Algeria, Antigua and Barbuda, Argentina, Austr...","Brunei, Cambodia, Cameroon, Canada, Cape Verde...","Arctic Ocean, Atlantic Ocean, Pacific Ocean",NaN,"[Oceanic pelagic zone, Marine, Neritic zone, E...","[Tropical, Temperate, Cold, Polar]","pod, gam, herd, school, mod","Aquatic, Precocial, Cosmopolitan, Natatorial, ...",Partial Migrant,Carnivore,Polygynandry,"year-round, usually in summer",15-18 months,1 calf,2 years,cow,bull,calf,NaN,NaN,Data deficient (DD)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29350,Córdoba cinclodes,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Cinclodes,Cinclodes comechingonus,NaN,NaN,NaN,NaN,NaN,NaN,"Terrestrial,Migrating,starts with",South America,NaN,Argentina,NaN,Neotropical,NaN,"[Grassland, Rocky areas ]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Least concern (LC)
29351,Western hemispingus,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Thraupidae,Sphenopsis,Sphenopsis ochracea,NaN,NaN,NaN,NaN,NaN,NaN,"Terrestrial,Not a migrant,starts with",South America,NaN,"Ecuador, Colombia",NaN,Neotropical,NaN,[Forest],[],NaN,"Terrestrial,",Not a migrant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,Least concern (LC)
29352,Sulphur-bearded reedhaunter,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Cranioleuca,Limnoctites sulphuriferus,NaN,NaN,NaN,NaN,NaN,NaN,"Terrestrial,Migrating,starts with",South America,NaN,"Argentina, Brazil, Uruguay",NaN,Neotropical,NaN,"[Freshwater, Shrubland, Wetlands ]",[],NaN,"Terrestrial,",Migrating,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Least concern (LC)
29355,McConnell's spinetail,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Synallaxis,Synallaxis macconnelli,NaN,NaN,NaN,NaN,NaN,NaN,"Terrestrial,Not a migrant,starts with",South America,NaN,"Brazil, Guyana, Suriname, Venezuela",French Guiana,Neotropical,NaN,"[Anthropogenic biome, Forest]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,Least concern (LC)
29356,Junín canastero,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Asthenes,Asthenes virgata,NaN,NaN,NaN,NaN,NaN,NaN,"Terrestrial,Not a migrant,starts with",South America,NaN,Peru,NaN,Neotropical,NaN,"[Grassland, Shrubland]",[],NaN,"Terrestrial,",Not a migrant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Least concern (LC)

Tại đây ta sẽ tách các cột có thuộc tính cách nhau bằng dấu phẩy thành 1 list

Luu vào "element" là tên các cột có các thuộc tính phân tách bằng dấu phẩy

Các cột sau khi xử lý sẽ được lưu vào biến "splits"

In [56]:
element = np.array(['Attributes', 'Continents', 'Subcontinents', 'Countries', 'Regions', 'Wwf biomes', 'Group name', 'Diet', 'Biogeographical realms', 'Lifestyle',  'Seasonal behavior'])

splits = [df_split_animals_info[col].str.split(pat = ',| and |  ', expand = False) for col in element]
splits = pd.DataFrame(splits).T
# print(splits.shape)
# print(splits.head())

Sau khi tách xong ta tiến hành ghép 2 dataframe lại thành "data_df"

In [57]:
df_split_animals_info.drop(element, axis=1, inplace=True)
data_df = pd.concat([df_split_animals_info, splits], axis = 1)
# data_df = data_df.drop(columns = data_df.columns[0], axis = 1)
data_df
# df_split_animals_info

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,Population size,Life span,Top speed,Weight,Height,Length,Biome,Climate,Mating behavior,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status,Attributes,Continents,Subcontinents,Countries,Regions,Wwf biomes,Group name,Diet,Biogeographical realms,Lifestyle,Seasonal behavior
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,"400,000",10-20 yrs,75 km/h,16-60 kg,80-85 cm,105-160 cm,"[Wetlands , Shrubland, Forest, Mountains, Anth...","[Temperate, Cold, Polar, Tropical]",Monogamy,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC),"[Nocturnal, Carnivore, Scavenger, Terrestrial,...","[Asia, Europe, North America, Africa]","[South Asia, Western Asia, Southeast Asia, ...","[Albania, Armenia, Azerbaijan, Belarus, Bh...","[Czech Republic, Estonia, Finland, France, ...","[Nearctic, Palearctic, Indomalayan, Afrotro...","[pack, route, rout]","[Carnivore, , Scavenger]",[Greenland],"[Terrestrial, Cursorial, Altricial, Pack hu...",[Not a migrant]
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,"2,154-3,159",10-15 yrs,96 km/h,65-306 kg,NaN,200-390 cm,"[Forest, Rainforest, Montane forest, Riparian,...","[Tropical, Temperate]",Polygyny,November-April,103 days,1-7 cubs,18 mos-3 yrs,NaN,NaN,cub,NaN,Decreasing,Endangered (EN),"[Nocturnal, Carnivore, Cursorial, Terrestrial,...",[Asia],"[South Asia, Southeast Asia, East Asia]","[Bangladesh, Bhutan, China, , India, Indon...",[Thailand],"[Palearctic, Indomalayan]",NaN,[Carnivore],"[Tibet, Yunnan]","[Cursorial, Terrestrial, Ambush predator, A...",[Not a migrant]
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,"200,000",20-50 yrs,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,"[Forest, Woodland]","[Temperate, Cold, Polar]","Polygynandry,",May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC),"[Crepuscular, Omnivore, Terrestrial, Altricial...","[Asia, Europe, North America]","[South Asia, Western Asia, East Asia, Centr...","[Albania, Armenia, Austria, Azerbaijan, Be...",NaN,"[Nearctic, Palearctic, Indomalayan]","[sloth, sleuth]",[Omnivore],"[Estonia, Finland, France, Georgia, Greece...","[Terrestrial, Altricial, Nomadic, Territori...","[Hibernating, Migrating]"
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,10-25 Thou,80-90 yrs,20 km/h,100-160 t,NaN,25-30 m,"[Oceanic pelagic zone, Marine, Neritic zone]","[Tropical, Temperate, Cold, Polar]",Monogamy,winter or early spring,1 year,1 calf,8 months,cow,bull,calf,NaN,Increasing,Endangered (EN),"[Carnivore, Piscivores, Aquatic, Precocial, Na...","[Africa, South America, Oceania, North Amer...","[Sub-Saharan Africa, Caribbean Islands, Sout...","[Angola, Argentina, Australia, Bahamas, Ba...","[Chile, China, Colombia, Comoros, Costa Ri...",NaN,"[pod, gam, herd, school, mod]","[Carnivore, , Piscivores]","[Atlantic Ocean, Pacific Ocean]","[Aquatic, Precocial, Natatorial, Viviparous...",[Migrating]
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,"50,000",30-100 yrs,45 km/h,3-6 t,NaN,6-9 m,"[Oceanic pelagic zone, Marine, Neritic zone, E...","[Tropical, Temperate, Cold, Polar]",Polygynandry,"year-round, usually in summer",15-18 months,1 calf,2 years,cow,bull,calf,NaN,NaN,Data deficient (DD),"[Diurnal, Carnivore, Aquatic, Precocial, Cosmo...","[Africa, Oceania, Antarctica, North America...","[North Africa, Caribbean Islands, South Asia...","[Algeria, Antigua, Barbuda, Argentina, Aust...","[Brunei, Cambodia, Cameroon, Canada, Cape ...",NaN,"[pod, gam, herd, school, mod]",[Carnivore],"[Arctic Ocean, Atlantic Ocean, Pacific Ocean]","[Aquatic, Precocial, Cosmopolitan, Natatori...",[Partial Migrant]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29350,Córdoba cinclodes,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Cinclodes,Cinclodes comechingonus,NaN,NaN,NaN,NaN,NaN,NaN,"[Grassland, Rocky areas ]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Least concern (LC),"[Terrestrial, Migrating, starts with]",[South America],NaN,[Argentina],NaN,NaN,NaN,NaN,[Neotropical],NaN,NaN
29351,Western hemispingus,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Thraupidae,Sphenopsis,Sphenopsis ochracea,NaN,NaN,NaN,NaN,NaN,NaN,[Forest],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,Least concern (LC),"[Terrestrial, Not a migrant, starts with]",[South America],NaN,"[Ecuador, Colombia]",NaN,NaN,NaN,NaN,[Neotropical],"[Terrestrial, ]",[Not a migrant]
29352,Sulphur-bearded reedhaunter,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Cranioleuca,Limnoctites sulphuriferus,NaN,NaN,NaN,NaN,NaN,NaN,"[Freshwater, Shrubland, Wetlands ]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Least concern (LC),"[Terrestrial, Migrating, starts with]",[South America],NaN,"[Argentina, Brazil, Uruguay]",NaN,NaN,NaN,NaN,[Neotropical],"[Terrestrial, ]",[Migrating]
29355,McConnell's spinetail,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Synallaxis,Synallaxis macconnelli,NaN,NaN,NaN,NaN,NaN,NaN,"[Anthropogenic biome, Forest]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,Least concern (LC),"[Terrestrial, Not a migrant, starts with]",[South America],NaN,"[Brazil, Guyana, Suriname, Venezuela]",[French Guiana],NaN,NaN,NaN,[Neotropical],NaN,NaN
29356,Junín canastero,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Asthenes,Asthenes virgata,NaN,NaN,NaN,NaN,NaN,NaN,"[Grassland, Shrubland]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Least concern (LC),"[Terrestrial, Not a migrant, starts with]",[South America],NaN,[Peru],NaN,NaN,NaN,NaN,[Neotropical],"[Terrestrial, ]",[Not a migrant]

Xử lý tại các cột list, những giá trị nan sẽ được thay thế thành một list rỗng []

In [58]:
data_df[element] = data_df[element].fillna(data_df.notna().applymap(lambda x: x or []))
# data_df = data_df.drop(columns = data_df.columns[0], axis = 1)
data_df

,Name,Kingdom,Phylum,Subphylum,Class,Order,Suborder,Family,Genus,Species,Population size,Life span,Top speed,Weight,Height,Length,Biome,Climate,Mating behavior,Reproduction season,Pregnancy duration,Baby carrying,Independent age,Female name,Male name,Baby name,Incubation period,Population trend,Population status,Attributes,Continents,Subcontinents,Countries,Regions,Wwf biomes,Group name,Diet,Biogeographical realms,Lifestyle,Seasonal behavior
0,Grey Wolf,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Canidae,Canis,Canis lupus,"400,000",10-20 yrs,75 km/h,16-60 kg,80-85 cm,105-160 cm,"[Wetlands , Shrubland, Forest, Mountains, Anth...","[Temperate, Cold, Polar, Tropical]",Monogamy,January-April,60-63 days,1-14 pups,45 days,bitch,dog,"pup, whelp",NaN,Stable,Least concern (LC),"[Nocturnal, Carnivore, Scavenger, Terrestrial,...","[Asia, Europe, North America, Africa]","[South Asia, Western Asia, Southeast Asia, ...","[Albania, Armenia, Azerbaijan, Belarus, Bh...","[Czech Republic, Estonia, Finland, France, ...","[Nearctic, Palearctic, Indomalayan, Afrotro...","[pack, route, rout]","[Carnivore, , Scavenger]",[Greenland],"[Terrestrial, Cursorial, Altricial, Pack hu...",[Not a migrant]
1,Tiger,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Feliformia,Felidae,Panthera,Panthera tigris,"2,154-3,159",10-15 yrs,96 km/h,65-306 kg,NaN,200-390 cm,"[Forest, Rainforest, Montane forest, Riparian,...","[Tropical, Temperate]",Polygyny,November-April,103 days,1-7 cubs,18 mos-3 yrs,NaN,NaN,cub,NaN,Decreasing,Endangered (EN),"[Nocturnal, Carnivore, Cursorial, Terrestrial,...",[Asia],"[South Asia, Southeast Asia, East Asia]","[Bangladesh, Bhutan, China, , India, Indon...",[Thailand],"[Palearctic, Indomalayan]",[],[Carnivore],"[Tibet, Yunnan]","[Cursorial, Terrestrial, Ambush predator, A...",[Not a migrant]
2,Brown Bear,Animalia,Chordata,Vertebrata,Mammalia,Carnivora,Caniformia,Ursidae,Ursus,Ursus arctos,"200,000",20-50 yrs,56 km/h,100-635 kg,70-153 cm,1.4-2.8 m,"[Forest, Woodland]","[Temperate, Cold, Polar]","Polygynandry,",May-July,8 weeks,1-4 cubs,2-4 years,sow,boar,cub,NaN,Stable,Least concern (LC),"[Crepuscular, Omnivore, Terrestrial, Altricial...","[Asia, Europe, North America]","[South Asia, Western Asia, East Asia, Centr...","[Albania, Armenia, Austria, Azerbaijan, Be...",[],"[Nearctic, Palearctic, Indomalayan]","[sloth, sleuth]",[Omnivore],"[Estonia, Finland, France, Georgia, Greece...","[Terrestrial, Altricial, Nomadic, Territori...","[Hibernating, Migrating]"
3,Blue Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Balaenopteridae,Balaenoptera,Balaenoptera musculus,10-25 Thou,80-90 yrs,20 km/h,100-160 t,NaN,25-30 m,"[Oceanic pelagic zone, Marine, Neritic zone]","[Tropical, Temperate, Cold, Polar]",Monogamy,winter or early spring,1 year,1 calf,8 months,cow,bull,calf,NaN,Increasing,Endangered (EN),"[Carnivore, Piscivores, Aquatic, Precocial, Na...","[Africa, South America, Oceania, North Amer...","[Sub-Saharan Africa, Caribbean Islands, Sout...","[Angola, Argentina, Australia, Bahamas, Ba...","[Chile, China, Colombia, Comoros, Costa Ri...",[],"[pod, gam, herd, school, mod]","[Carnivore, , Piscivores]","[Atlantic Ocean, Pacific Ocean]","[Aquatic, Precocial, Natatorial, Viviparous...",[Migrating]
4,Killer Whale,Animalia,Chordata,Vertebrata,Mammalia,Artiodactyla,NaN,Delphinidae,Orcinus,Orcinus orca,"50,000",30-100 yrs,45 km/h,3-6 t,NaN,6-9 m,"[Oceanic pelagic zone, Marine, Neritic zone, E...","[Tropical, Temperate, Cold, Polar]",Polygynandry,"year-round, usually in summer",15-18 months,1 calf,2 years,cow,bull,calf,NaN,NaN,Data deficient (DD),"[Diurnal, Carnivore, Aquatic, Precocial, Cosmo...","[Africa, Oceania, Antarctica, North America...","[North Africa, Caribbean Islands, South Asia...","[Algeria, Antigua, Barbuda, Argentina, Aust...","[Brunei, Cambodia, Cameroon, Canada, Cape ...",[],"[pod, gam, herd, school, mod]",[Carnivore],"[Arctic Ocean, Atlantic Ocean, Pacific Ocean]","[Aquatic, Precocial, Cosmopolitan, Natatori...",[Partial Migrant]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29350,Córdoba cinclodes,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Cinclodes,Cinclodes comechingonus,NaN,NaN,NaN,NaN,NaN,NaN,"[Grassland, Rocky areas ]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Least concern (LC),"[Terrestrial, Migrating, starts with]",[South America],[],[Argentina],[],[],[],[],[Neotropical],[],[]
29351,Western hemispingus,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Thraupidae,Sphenopsis,Sphenopsis ochracea,NaN,NaN,NaN,NaN,NaN,NaN,[Forest],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,Least concern (LC),"[Terrestrial, Not a migrant, starts with]",[South America],[],"[Ecuador, Colombia]",[],[],[],[],[Neotropical],"[Terrestrial, ]",[Not a migrant]
29352,Sulphur-bearded reedhaunter,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Cranioleuca,Limnoctites sulphuriferus,NaN,NaN,NaN,NaN,NaN,NaN,"[Freshwater, Shrubland, Wetlands ]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decreasing,Least concern (LC),"[Terrestrial, Migrating, starts with]",[South America],[],"[Argentina, Brazil, Uruguay]",[],[],[],[],[Neotropical],"[Terrestrial, ]",[Migrating]
29355,McConnell's spinetail,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Synallaxis,Synallaxis macconnelli,NaN,NaN,NaN,NaN,NaN,NaN,"[Anthropogenic biome, Forest]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stable,Least concern (LC),"[Terrestrial, Not a migrant, starts with]",[South America],[],"[Brazil, Guyana, Suriname, Venezuela]",[French Guiana],[],[],[],[Neotropical],[],[]
29356,Junín canastero,Animalia,Chordata,NaN,Aves,Passeriformes,NaN,Furnariidae,Asthenes,Asthenes virgata,NaN,NaN,NaN,NaN,NaN,NaN,"[Grassland, Shrubland]",[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,Least concern (LC),"[Terrestrial, Not a migrant, starts with]",[South America],[],[Peru],[],[],[],[],[Neotropical],"[Terrestrial, ]",[Not a migrant]

### Chuyển cột Top speed sang kiểu số

In [59]:
def to_float(element):
    try:
        return float(element)
    except ValueError:
        return np.nan

In [60]:
def trans_speed(speed):
    if pd.isna(speed): return np.nan
    speed = [speed[:-4].strip(), speed[-4:].strip()]
    if speed[1] == 'km/h':
        x = 1
    elif speed[1] == 'mph':
        x = 1.61
    sp = speed[0].split('-')
    if len(sp) == 1:
        return float(sp[0]) * x
    else:
        return (float(sp[0]) + float(sp[1])) / 2 * x

In [61]:
data_df['Top speed'] = data_df['Top speed'].apply(trans_speed)

### Chuyển cột life_span sang float

In [62]:
def trans_life_span(life):
    if pd.isna(life): return np.nan
    life = str(life)
    life = life.upper()
    life = life.replace('UPPER', '')
    life = life.replace('ABOVE', '')
    life = life.replace('OVER','')
    life = life.replace('mos', ' MONTHS ')
    life = life.replace('yr', ' YEARS ')
    life = life.replace('YRS', ' YEARS ')
    life = life.replace('YEARS', ' YEARS ')
    life = life.split('-')
    low = to_float(life[0])
    high = to_float(life[-1].split()[0].strip())
    x = life[-1].split()[-1].strip()
    if np.isnan(low):
        low = high
    t = 1.0
    if x == 'MONTHS':
        t = 1 / 12
    elif x == 'YEARS':
        t = 1.0
    low = low * t
    high = high * t
    return (low, high)

In [63]:
data_df['Life span'] = data_df['Life span'].apply(trans_life_span)
#data_df['Life span'].dropna()

## Thống kê các chỉ số cho các cột có kiểu dữ liệu là list

In [64]:
def stat_list_col(col, array):
    temp = pd.DataFrame(array[col])
    temp = temp.dropna()
    temp = np.array(temp[col])
    data = []
    # missing_ratio
    data.append(round((100 - (len(temp) / len(array[col]) * 100)), 1))
    # num_values
    temp = np.hstack(temp)
    temp = list(map(str.strip, temp)) # Xử lý các dấu cách đầu và cuối mỗi chuỗi
    temp = np.unique(temp, return_counts=True)
    data.append(len(temp[0]))
    # value
    temp = pd.Series(data = temp[1], index = temp[0])
    data.append(temp)
    # num_values
    return data

#     total = data_df[col].tolist()
#     total = np.hstack(total)
#     value, times = np.unique(total, return_counts = True)

In [65]:
list_col_info_df = pd.DataFrame(index = ['missing_ratio', 'num_values', 'value'])
for i in data_df:
    if type(data_df[i][0]) == list:
        list_col_info_df[i] = stat_list_col(i, data_df)
    pd.set_option('display.max_columns', None)

list_col_info_df

,Biome,Climate,Attributes,Continents,Subcontinents,Countries,Regions,Wwf biomes,Group name,Diet,Biogeographical realms,Lifestyle,Seasonal behavior
missing_ratio,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
num_values,43,6,139,132,80,258,423,266,400,30,419,47,8
value,Abyssal zone 4 Agricultural ...,Arid 299 Cold 305 Libya ...,Aestivation 71 Algivore ...,11908 Africa 191...,40 Afghanistan 1 Afro...,6611 Afghanistan 95 ...,1120 Acre 6 ...,179 Afghanistan ...,"1 ""bind"" 1 ""littl...",2972 Algivore 18 ...,600 Afgha...,9659 Aestivation ...,...

### Lưu dữ liệu đã tiền xử lý vào file 'animals_split_info.csv' để tiếp tục sử dụng trong các phần sau

In [71]:
data_df.to_csv('animals_split_info.csv')